Lee-W/cookiecutter-python-template

- .pre-commit-config.yaml
- cookiecutter.json
- docs/README.md
- hooks/post_gen_project.py
- poetry.lock
- pyproject.toml
- pytest.ini
- setup.cfg
- tasks/test.py
- tests/test_bake_project.py
- {{cookiecutter.project_slug}}/.github/workflows/python-check.yaml
- {{cookiecutter.project_slug}}/.github/workflows/python-publish.yaml
- {{cookiecutter.project_slug}}/.pre-commit-config.yaml
- {{cookiecutter.project_slug}}/LICENSE
- {{cookiecutter.project_slug}}/Pipfile
- {{cookiecutter.project_slug}}/pyproject.toml
- {{cookiecutter.project_slug}}/setup.cfg
- {{cookiecutter.project_slug}}/tasks/build.py
- {{cookiecutter.project_slug}}/tasks/env.py
* docs(project-root): add detailed usage to README
* style: update mypy version and fix format
* test: test running style and pre-commit after project setup
* fix(docker): rename add_general_dockerfile as build_docker_image and move hadolint to template from project root
* feat(tasks/env): add autoupdate to pre-commit
* feat(pre-commit): add check-case-conflict, check-merge-conflict, no-commit-to-branch and change style format stage to commit
* feat(github-actions): add workflow-dispatch to python-check
* fix(license): fix end of line
* feat(mypy): migrate configuration to pyproject.toml
* style(mypy): migrate mypy configurtaion to pyproject.toml
* style(project-root): migrate pytest configuration to pyproject.toml
> Migrate mypy config to pyproject toml

- {{cookiecutter.project_slug}}/tasks/build.py
> fix(tasks/build): fix missing import when pipenv is used

- .github/workflows/master-updated.yaml
- .github/workflows/pushed.yaml
- docs/README.md
- poetry.lock
- pyproject.toml
- tasks/style.py
- {{cookiecutter.project_slug}}/tasks/style.py
- **Bugfix**
* fix(tasks/style): fix commit check command
* docs(project-root): use cruft to replace cookiecutter
* docs(project-root): add badges to project-root
* feat(project-root): upgrade project-root python version to 3.10 and upgrade deps
> Update python version

- .github/workflows/master-updated.yaml
> fix(github-actions): use personal access token to replace github token

- .github/workflows/master-updated.yaml
- {{cookiecutter.project_slug}}/.github/workflows/{{cookiecutter.default_branch}}-updated.yaml
> fix(github-actions): set persist-credentials to false for check-out actions

- poetry.lock
- pyproject.toml
- tasks/secure.py
- {{cookiecutter.project_slug}}/.github/workflows/python-check.yaml
- {{cookiecutter.project_slug}}/.github/workflows/python-publish.yaml
- {{cookiecutter.project_slug}}/.github/workflows/{{cookiecutter.default_branch}}-updated.yaml
- {{cookiecutter.project_slug}}/.pre-commit-config.yaml
- {{cookiecutter.project_slug}}/Pipfile
- {{cookiecutter.project_slug}}/docs/README.md
- {{cookiecutter.project_slug}}/pyproject.toml
- {{cookiecutter.project_slug}}/tasks/secure.py
> fix: fix various minor errors

- CHANGELOG.md
- cookiecutter.json
- docs/README.md
- tasks/env.py
- tasks/secure.py
- tasks/style.py
- tests/test_bake_project.py
- {{cookiecutter.project_slug}}/tasks/env.py
- {{cookiecutter.project_slug}}/tasks/secure.py
- {{cookiecutter.project_slug}}/tasks/style.py
- {{cookiecutter.project_slug}}/tasks/test.py
- **Style**
Fix typo
Greate repository, fixing the typos makes it even better
None
> style(type): fix typos

- .github/dependabot.yml
- {{cookiecutter.project_slug}}/.github/dependabot.yml
> feat: add dependabot setup

- poetry.lock
- pyproject.toml
- tasks/secure.py
- {{cookiecutter.project_slug}}/Pipfile
- {{cookiecutter.project_slug}}/pyproject.toml
- {{cookiecutter.project_slug}}/tasks/secure.py
- upgrade mypy and invoke
-  fix docstring inconsistency
> Upgrade mypy

- .github/workflows/master-updated.yaml
- poetry.lock
> fix gh-page publish failure

- .github/workflows/master-updated.yaml
> ci(github-actions): fix gh-pages update secret loading error

- poetry.lock
- pyproject.toml
- **Other (please describe)** Dependency
Fix project-root dependency
> build(project-root): fix deps

- {{cookiecutter.project_slug}}/tasks/__init__.py
> fix(tasks): fix import error

- .github/workflows/pushed.yaml
- {{cookiecutter.project_slug}}/.github/workflows/python-check.yaml
- **Bugfix**
fix(github-actions): skip no-commit-to-branch in CI which causes false negative when bumping version
> fix(github-actions): skip no-commit-to-branch in CI which causes false negative when bumping version

- .github/workflows/pushed.yaml
- tasks/__init__.py
- {{cookiecutter.project_slug}}/.github/workflows/python-check.yaml
- {{cookiecutter.project_slug}}/tasks/__init__.py
- **Bugfix**
fix(tasks): fix missing hook-stage in run-pre-commit-hooks task
> fix(tasks): fix missing hook-stage in run-pre-commit-hooks task

- .pre-commit-config.yaml
- pyproject.toml
- tasks/style.py
- {{cookiecutter.project_slug}}/.pre-commit-config.yaml
- {{cookiecutter.project_slug}}/docs/contributing.md
- {{cookiecutter.project_slug}}/pyproject.toml
- {{cookiecutter.project_slug}}/tasks/style.py
> feat: upgrade ruff related config due to ruff upgrade

- poetry.lock
- {{cookiecutter.project_slug}}/.pre-commit-config.yaml
> Fix pre commit config

- pyproject.toml
> build(project-root): update-deps

- .github/workflows/main-updated.yaml
- .github/workflows/pushed.yaml
- cookiecutter.json
- docs/README.md
- pyproject.toml
- tests/test_bake_project.py
- uv.lock
- {{cookiecutter.project_slug}}/.github/workflows/cruft-update.yaml
- {{cookiecutter.project_slug}}/.github/workflows/python-check.yaml
- {{cookiecutter.project_slug}}/.github/workflows/python-publish.yaml
- {{cookiecutter.project_slug}}/.github/workflows/{{cookiecutter.default_branch}}-updated.yaml
- {{cookiecutter.project_slug}}/.pre-commit-config.yaml
- {{cookiecutter.project_slug}}/Pipfile
- {{cookiecutter.project_slug}}/docs/contributing.md
- {{cookiecutter.project_slug}}/mkdocs.yml
- {{cookiecutter.project_slug}}/pyproject.toml
- {{cookiecutter.project_slug}}/tasks/build.py
- {{cookiecutter.project_slug}}/tasks/env.py
> Add uv support

- .github/workflows/main-updated.yaml
- .github/workflows/pushed.yaml
- .pre-commit-config.yaml
- cookiecutter.json
- docs/README.md
- hooks/post_gen_project.py
- pyproject.toml
- tests/test_bake_project.py
- uv.lock
- {{cookiecutter.project_slug}}/.github/workflows/cruft-update.yaml
- {{cookiecutter.project_slug}}/.github/workflows/python-check.yaml
- {{cookiecutter.project_slug}}/.github/workflows/python-publish.yaml
- {{cookiecutter.project_slug}}/.github/workflows/{{cookiecutter.default_branch}}-updated.yaml
- {{cookiecutter.project_slug}}/.markdownlint.yaml
- {{cookiecutter.project_slug}}/.pre-commit-config.yaml
- {{cookiecutter.project_slug}}/Dockerfile
- {{cookiecutter.project_slug}}/Pipfile
- {{cookiecutter.project_slug}}/docs/README.md
- {{cookiecutter.project_slug}}/docs/contributing.md
- {{cookiecutter.project_slug}}/mkdocs.yml
- {{cookiecutter.project_slug}}/pyproject.toml
- {{cookiecutter.project_slug}}/tasks/build.py
- {{cookiecutter.project_slug}}/tasks/env.py
- **Bugfix**
* breaking change
* feat(cookiecutter)
* make python version a choice
* Use boolean variable in cookiecutter.json
* feat
* add uv support
* migrate pre-commit config
* group Pipfile, pyproject.toml dependencies
* poetry
* add package-mode support
* pre-commit
* add markdownlint and spellcheck
* spellcheck
* initialize spelling worklist
* fix(github-actions)
* fix cruft-update python version
* unify actions/setup-python version
* unify actions/checkout version
* fix(Dockerfile): fix hadolint warning
> Release v2 template

- CHANGELOG.md
> docs(CHANGELOG): fix typo

- cookiecutter.json
- tests/test_bake_project.py
- uv.lock
- {{cookiecutter.project_slug}}/pyproject.toml
- {{cookiecutter.project_slug}}/tasks/env.py
Upgrade minimum poetry version to >= 2.0 and use the [PEP621](https://peps.python.org/pep-0621/) spec
> Upgrade minimum poetry to 2.0
